const data = {
    id: "MLA741093357",
    site_id: "MLA",
    title: "Peluche Stitch Angel Lilo 1 Metro 100cm Reales Gigante",
    subtitle: null,
    seller_id: 298424621,
    category_id: "MLA1166",
    official_store_id: null,
    price: 13999,
    base_price: 13999,
    original_price: null,
    currency_id: "ARS",
    initial_quantity: 76,
    available_quantity: 1,
    sold_quantity: 50,
    sale_terms: [],
    buying_mode: "buy_it_now",
    listing_type_id: "gold_special",
    start_time: "2018-08-04T02:27:28.000Z",
    stop_time: "2038-07-29T04:00:00.000Z",
    condition: "new",
    permalink:
        "https://articulo.mercadolibre.com.ar/MLA-741093357-peluche-stitch-angel-lilo-1-metro-100cm-reales-gigante-_JM",
    thumbnail_id: "978173-MLA32582347639_102019",
    thumbnail: "http://http2.mlstatic.com/D_978173-MLA32582347639_102019-I.jpg",
    secure_thumbnail:
        "https://http2.mlstatic.com/D_978173-MLA32582347639_102019-I.jpg",
    pictures: [
        {
            id: "978173-MLA32582347639_102019",
            url: "http://http2.mlstatic.com/D_978173-MLA32582347639_102019-O.jpg",
            secure_url:
                "https://http2.mlstatic.com/D_978173-MLA32582347639_102019-O.jpg",
            size: "500x496",
            max_size: "1200x1192",
            quality: "",
        },
        {
            id: "754004-MLA32299823528_092019",
            url: "http://http2.mlstatic.com/D_754004-MLA32299823528_092019-O.jpg",
            secure_url:
                "https://http2.mlstatic.com/D_754004-MLA32299823528_092019-O.jpg",
            size: "500x396",
            max_size: "1200x951",
            quality: "",
        },
        {
            id: "616691-MLA27900381255_082018",
            url: "http://http2.mlstatic.com/D_616691-MLA27900381255_082018-O.jpg",
            secure_url:
                "https://http2.mlstatic.com/D_616691-MLA27900381255_082018-O.jpg",
            size: "500x500",
            max_size: "800x800",
            quality: "",
        },
        {
            id: "918230-MLA31424182281_072019",
            url: "http://http2.mlstatic.com/D_918230-MLA31424182281_072019-O.jpg",
            secure_url:
                "https://http2.mlstatic.com/D_918230-MLA31424182281_072019-O.jpg",
            size: "281x500",
            max_size: "1080x1920",
            quality: "",
        },
    ],
    video_id: null,
    descriptions: [
        {
            id: "MLA741093357-1768858232",
        },
    ],
    accepts_mercadopago: true,
    non_mercado_pago_payment_methods: [],
    shipping: {
        mode: "me2",
        free_methods: [
            {
                id: 73328,
                rule: {
                    default: true,
                    free_mode: "country",
                    free_shipping_flag: true,
                    value: null,
                },
            },
        ],
        tags: ["self_service_in", "mandatory_free_shipping"],
        dimensions: null,
        local_pick_up: true,
        free_shipping: true,
        logistic_type: "drop_off",
        store_pick_up: false,
    },
    international_delivery_mode: "none",
    seller_address: {
        city: {
            id: "TUxBQlZJTDE2MDBa",
            name: "Villa Pueyrredón",
        },
        state: {
            id: "AR-C",
            name: "Capital Federal",
        },
        country: {
            id: "AR",
            name: "Argentina",
        },
        search_location: {
            neighborhood: {
                id: "TUxBQlZJTDE2MDBa",
                name: "Villa Pueyrredón",
            },
            city: {
                id: "TUxBQ0NBUGZlZG1sYQ",
                name: "Capital Federal",
            },
            state: {
                id: "TUxBUENBUGw3M2E1",
                name: "Capital Federal",
            },
        },
        id: 859653629,
    },
    seller_contact: null,
    location: {},
    coverage_areas: [],
    attributes: [
        {
            id: "MAX_RECOMMENDED_AGE",
            name: "Edad máxima recomendada",
            value_id: null,
            value_name: "99 años",
            value_struct: {
                number: 99,
                unit: "años",
            },
            values: [
                {
                    id: null,
                    name: "99 años",
                    struct: {
                        number: 99,
                        unit: "años",
                    },
                },
            ],
            attribute_group_id: "",
            attribute_group_name: "",
        },
        {
            id: "PRODUCT_TYPE",
            name: "Tipo de producto",
            value_id: null,
            value_name: "peluche",
            value_struct: null,
            values: [
                {
                    id: null,
                    name: "peluche",
                    struct: null,
                },
            ],
            attribute_group_id: "",
            attribute_group_name: "",
        },
        {
            id: "ANIMAL",
            name: "Animal",
            value_id: null,
            value_name: "stitch",
            value_struct: null,
            values: [
                {
                    id: null,
                    name: "stitch",
                    struct: null,
                },
            ],
            attribute_group_id: "OTHERS",
            attribute_group_name: "Otros",
        },
        {
            id: "BRAND",
            name: "Marca",
            value_id: "33243",
            value_name: "Disney",
            value_struct: null,
            values: [
                {
                    id: "33243",
                    name: "Disney",
                    struct: null,
                },
            ],
            attribute_group_id: "OTHERS",
            attribute_group_name: "Otros",
        },
        {
            id: "CHARACTER",
            name: "Personaje",
            value_id: "4959202",
            value_name: "Stitch",
            value_struct: null,
            values: [
                {
                    id: "4959202",
                    name: "Stitch",
                    struct: null,
                },
            ],
            attribute_group_id: "OTHERS",
            attribute_group_name: "Otros",
        },
        {
            id: "FRANCHISE",
            name: "Franquicia",
            value_id: null,
            value_name: "Stitch",
            value_struct: null,
            values: [
                {
                    id: null,
                    name: "Stitch",
                    struct: null,
                },
            ],
            attribute_group_id: "OTHERS",
            attribute_group_name: "Otros",
        },
        {
            id: "GTIN",
            name: "Código universal de producto",
            value_id: null,
            value_name: "8480017059031",
            value_struct: null,
            values: [
                {
                    id: null,
                    name: "8480017059031",
                    struct: null,
                },
            ],
            attribute_group_id: "OTHERS",
            attribute_group_name: "Otros",
        },
        {
            id: "HEIGHT",
            name: "Altura",
            value_id: null,
            value_name: "100 cm",
            value_struct: {
                number: 100,
                unit: "cm",
            },
            values: [
                {
                    id: null,
                    name: "100 cm",
                    struct: {
                        number: 100,
                        unit: "cm",
                    },
                },
            ],
            attribute_group_id: "OTHERS",
            attribute_group_name: "Otros",
        },
        {
            id: "IS_HYPOALLERGENIC_MATERIAL",
            name: "Es material hipoalergénico",
            value_id: "242085",
            value_name: "Sí",
            value_struct: null,
            values: [
                {
                    id: "242085",
                    name: "Sí",
                    struct: null,
                },
            ],
            attribute_group_id: "OTHERS",
            attribute_group_name: "Otros",
        },
        {
            id: "ITEM_CONDITION",
            name: "Condición del ítem",
            value_id: "2230284",
            value_name: "Nuevo",
            value_struct: null,
            values: [
                {
                    id: "2230284",
                    name: "Nuevo",
                    struct: null,
                },
            ],
            attribute_group_id: "OTHERS",
            attribute_group_name: "Otros",
        },
        {
            id: "MATERIAL",
            name: "Material",
            value_id: "462324",
            value_name: "Plush",
            value_struct: null,
            values: [
                {
                    id: "462324",
                    name: "Plush",
                    struct: null,
                },
            ],
            attribute_group_id: "OTHERS",
            attribute_group_name: "Otros",
        },
        {
            id: "MIN_RECOMMENDED_AGE",
            name: "Edad mínima recomendada",
            value_id: null,
            value_name: "0 años",
            value_struct: {
                number: 0,
                unit: "años",
            },
            values: [
                {
                    id: null,
                    name: "0 años",
                    struct: {
                        number: 0,
                        unit: "años",
                    },
                },
            ],
            attribute_group_id: "OTHERS",
            attribute_group_name: "Otros",
        },
        {
            id: "MODEL",
            name: "Modelo",
            value_id: null,
            value_name: "Stitch",
            value_struct: null,
            values: [
                {
                    id: null,
                    name: "Stitch",
                    struct: null,
                },
            ],
            attribute_group_id: "OTHERS",
            attribute_group_name: "Otros",
        },
        {
            id: "SELLER_SKU",
            name: "SKU",
            value_id: null,
            value_name: "1metro",
            value_struct: null,
            values: [
                {
                    id: null,
                    name: "1metro",
                    struct: null,
                },
            ],
            attribute_group_id: "OTHERS",
            attribute_group_name: "Otros",
        },
        {
            id: "WIDTH",
            name: "Ancho",
            value_id: null,
            value_name: "50 cm",
            value_struct: {
                number: 50,
                unit: "cm",
            },
            values: [
                {
                    id: null,
                    name: "50 cm",
                    struct: {
                        number: 50,
                        unit: "cm",
                    },
                },
            ],
            attribute_group_id: "OTHERS",
            attribute_group_name: "Otros",
        },
    ],
    warnings: [],
    listing_source: "",
    variations: [],
    status: "active",
    sub_status: [],
    tags: [
        "good_quality_thumbnail",
        "loyalty_discount_eligible",
        "brand_verified",
        "good_quality_picture",
        "immediate_payment",
        "cart_eligible",
    ],
    warranty: null,
    catalog_product_id: null,
    domain_id: "MLA-STUFFED_TOYS",
    parent_item_id: null,
    differential_pricing: null,
    deal_ids: [],
    automatic_relist: false,
    date_created: "2018-08-04T02:27:28.000Z",
    last_updated: "2021-05-04T14:10:53.000Z",
    health: 0.88,
    catalog_listing: false,
    channels: ["marketplace"],
    preguntas: [
        {
            pregunta: "Hola, lo tenes en negro?",
            respuesta: "Si, lo tenemos disponible",
            fecha: "10-08-2022",
        },
        {
            pregunta: "Hacen envíos a todo el país?",
            respuesta: "Si, hacemos envíos a todo el país.",
            fecha: "12-08-2022",
        },
        {
            pregunta: "Hola, tenes stock?",
            respuesta: "Si, tenemos stock disponible",
            fecha: "08-08-2022",
        },
    ],
    promocionados: [
        {
            id: 1,
            img: "https://http2.mlstatic.com/D_Q_NP_2X_649746-MLA46415134138_062021-AB.webp",
            price: 24800,
            desc: "Peluche Oso Gigante Sentado Phi Phi Toys 1.90mts Parado",
        },
        {
            id: 2,
            img: "https://http2.mlstatic.com/D_Q_NP_2X_737150-MLA42756987304_072020-AB.webp",
            price: 15600,
            desc: "Peluche Gigante Cienpies Didactico 1.5mts",
        },
        {
            id: 3,
            img: "https://http2.mlstatic.com/D_Q_NP_2X_862938-MLA47306814342_082021-AB.webp",
            price: 13853,
            desc: "Peluches Squishmallows Mini Playset House",
        },
        {
            id: 4,
            img: "https://http2.mlstatic.com/D_Q_NP_2X_790452-MLA49051242763_022022-AB.webp",
            price: 3145,
            desc: "Peluches Almohada Animalitos 46cm Perro Chancho X",
        },
    ],
    otherProducts: [
        {
            name: "LARIX TOYS",
            img: "https://http2.mlstatic.com/D_Q_NP_760782-MLA50509447716_062022-AB.webp",
            desc: "Oso de Peluche Gigante 1,1m Grande Marron",
            price: 13205,
        },
        {
            name: "INFANCENTER",
            img: "https://http2.mlstatic.com/D_Q_NP_976907-MLA43261987950_082020-AB.webp",
            desc: "Peluche De Stich - Con Sonido",
            price: 8819,
        },
        {
            name: "INFANCENTER",
            img: "https://http2.mlstatic.com/D_Q_NP_976907-MLA43261987950_082020-AB.webp",
            desc: "Peluche De Stich Con Sonido",
            price: 8819,
        },
        {
            name: "INFANCENTER",
            img: "https://http2.mlstatic.com/D_Q_NP_659034-MLA50320967170_062022-AB.webp",
            desc: "Set Peluches Ositos Cariñositos 3 personajes",
            price: 26459,
        },
    ],
    carousel: [
        {
            id: 1,
            name: "LARIX TOYS",
            img: "https://http2.mlstatic.com/D_Q_NP_760782-MLA50509447716_062022-AB.webp",
            desc: "Oso de Peluche Gigante 1,1m Grande Marron",
            price: 13205,
        },
        {
            id: 3,
            name: "INFANCENTER",
            img: "https://http2.mlstatic.com/D_Q_NP_976907-MLA43261987950_082020-AB.webp",
            desc: "Peluche De Stich Con Sonido",
            price: 8819,
        },
        {
            id: 4,
            name: "INFANCENTER",
            img: "https://http2.mlstatic.com/D_Q_NP_659034-MLA50320967170_062022-AB.webp",
            desc: "Set Peluches Ositos Cariñositos 3 personajes",
            price: 26459,
        },
        {
            id: 5,
            img: "https://http2.mlstatic.com/D_Q_NP_2X_649746-MLA46415134138_062021-AB.webp",
            price: 24800,
            desc: "Peluche Oso Gigante Sentado Phi Phi Toys 1.90mts Parado",
        },
        {
            id: 6,
            img: "https://http2.mlstatic.com/D_Q_NP_2X_737150-MLA42756987304_072020-AB.webp",
            price: 15600,
            desc: "Peluche Gigante Cienpies Didactico 1.5mts",
        },
        {
            id: 2,
            name: "INFANCENTER",
            img: "https://http2.mlstatic.com/D_Q_NP_976907-MLA43261987950_082020-AB.webp",
            desc: "Peluche De Stich - Con Sonido",
            price: 8819,
        },
        {
            id: 7,
            img: "https://http2.mlstatic.com/D_Q_NP_2X_862938-MLA47306814342_082021-AB.webp",
            price: 13853,
            desc: "Peluches Squishmallows Mini Playset House",
        },
        {
            id: 8,
            img: "https://http2.mlstatic.com/D_Q_NP_2X_790452-MLA49051242763_022022-AB.webp",
            price: 3145,
            desc: "Peluches Almohada Animalitos 46cm Perro Chancho X",
        },
    ],
};
export default data;
